name: flutter_app_link_checker
description: Flutter & Dart automation tool to audit and detect 404 broken links in Flutter apps, WebViews, and Deep Links.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
